"""fix enum

Revision ID: 23eaa4b738f1
Revises: 8c4a972a3413
Create Date: 2025-08-13 13:03:56.859324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23eaa4b738f1"
down_revision: Union[str, None] = "8c4a972a3413"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice_hospitalized", sa.Column("status", sa.Integer(), nullable=False)
    )
    op.add_column("invoice_medical", sa.Column("status", sa.Integer(), nullable=False))
    op.alter_column(
        "invoice_prescription",
        "status",
        existing_type=postgresql.ENUM(
            "UNFINISHED", "COMPLETED", name="statusinvoiceenum"
        ),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using=(
            "CASE "
            "WHEN status = 'UNFINISHED' THEN 1 "
            "WHEN status = 'COMPLETED' THEN 2 "
            "END"
        ),
    )
    op.alter_column(
        "users",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", "OTHER", name="genderenum"),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using=(
            "CASE "
            "WHEN gender = 'MALE' THEN 1 "
            "WHEN gender = 'FEMALE' THEN 2 "
            "WHEN gender = 'OTHER' THEN 3 "
            "END"
        ),
    )
    op.execute("DROP TYPE IF EXISTS statusinvoiceenum CASCADE")
    op.execute("DROP TYPE IF EXISTS genderenum CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = postgresql.ENUM("MALE", "FEMALE", "OTHER", name="genderenum")
    status_invoice_enum = postgresql.ENUM(
        "UNFINISHED", "COMPLETED", name="statusinvoiceenum"
    )

    gender_enum.create(op.get_bind(), checkfirst=True)
    status_invoice_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "users",
        "gender",
        existing_type=sa.Integer(),
        type_=postgresql.ENUM("MALE", "FEMALE", "OTHER", name="genderenum"),
        existing_nullable=False,
    )
    op.alter_column(
        "invoice_prescription",
        "status",
        existing_type=sa.Integer(),
        type_=postgresql.ENUM("UNFINISHED", "COMPLETED", name="statusinvoiceenum"),
        existing_nullable=False,
    )
    op.drop_column("invoice_medical", "status")
    op.drop_column("invoice_hospitalized", "status")
    # ### end Alembic commands ###
