"""init1

Revision ID: 6f319ed74f06
Revises: 17a8f553b32f
Create Date: 2025-08-12 23:26:38.657745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f319ed74f06'
down_revision: Union[str, None] = '17a8f553b32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batch', sa.Column('initial_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_batch', 'initial_quantity')
    # ### end Alembic commands ###
