"""migration new

Revision ID: c061ef2871f2
Revises: 4a6c04b4eeee
Create Date: 2025-08-07 11:23:27.397372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c061ef2871f2"
down_revision: Union[str, None] = "4a6c04b4eeee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("permission_id", sa.Integer(), nullable=True),
        sa.Column("list_method", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("permission_id", "role_id", name="uq_role_permission"),
    )
    op.drop_table("role_menu")
    op.drop_table("menu")
    op.drop_table("schedule_appointment_detail")
    op.alter_column(
        "appointment", "cancel_reason", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "schedule_doctor",
        "end_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule_doctor",
        "end_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "appointment", "cancel_reason", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_table(
        "schedule_appointment_detail",
        sa.Column(
            "schedule_doctor_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("appointment_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "start_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "end_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
            name="schedule_appointment_detail_appointment_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_doctor_id"],
            ["schedule_doctor.id"],
            name="schedule_appointment_detail_schedule_doctor_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="schedule_appointment_detail_pkey"),
        sa.UniqueConstraint(
            "appointment_id", name="schedule_appointment_detail_appointment_id_key"
        ),
    )
    op.create_table(
        "menu",
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('menu_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="menu_pkey"),
        sa.UniqueConstraint("path", name="menu_path_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "role_menu",
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("menu_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "list_method",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["menu_id"], ["menu.id"], name="role_menu_menu_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name="role_menu_role_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="role_menu_pkey"),
        sa.UniqueConstraint("menu_id", "role_id", name="uq_menu_role"),
    )
    op.drop_table("role_permission")
    op.drop_table("permissions")
    # ### end Alembic commands ###
